sudo: required
services: docker
language: bash
env:
    global:
      - QEMU_VER=v2.9.1
      - DOCKER_REPO=maartje/registry-multiarch
    matrix:
      - ARCH=amd64 QEMU_ARCH=x86_64   GO_ARCH=amd64   VERSION=2.6.2
      - ARCH=armhf QEMU_ARCH=arm      GO_ARCH=armv6l  VERSION=2.6.2
      - ARCH=arm64 QEMU_ARCH=aarch64  GO_ARCH=arm64   VERSION=2.6.2

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - sudo apt-get -y install qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register
script:
  - travis_wait sudo ./build.sh --arch="$ARCH" --qemuarch="$QEMU_ARCH" --qemuversion="$QEMU_VER" --goarch="$GO_ARCH" --version="$VERSION"
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_REPO